"""Extract expected-output transcripts from executed solution notebooks.

Run after build_notebooks.sh has executed the solution notebooks in place.
For each solutions/<name>_solutions.ipynb passed on the command line (as
<name>), write solutions/transcripts/<name>_expected_output.txt containing
the text of every stream/execute_result output, in cell order.
"""

import json
import sys
from pathlib import Path

SOL = Path(__file__).resolve().parent / "solutions"
OUT = SOL / "transcripts"


def transcript(nb_path: Path) -> str:
    nb = json.loads(nb_path.read_text())
    name = nb_path.stem.replace("_solutions", "")
    lines = [
        f"EXPECTED OUTPUT — {name} (SOLUTION)",
        'Captured by an offline run (OPENAI_API_KEY=""), so model cells show',
        "the canned fallbacks; live runs will differ in wording, not in the",
        "verified numbers. Use as the read-along fallback if the API is down.",
        "",
    ]
    errors = 0
    for cell in nb.get("cells", []):
        if cell.get("cell_type") != "code":
            continue
        for o in cell.get("outputs", []):
            kind = o.get("output_type")
            if kind == "stream":
                lines.append("".join(o.get("text", "")).rstrip())
            elif kind in ("execute_result", "display_data"):
                txt = o.get("data", {}).get("text/plain")
                if txt:
                    lines.append("".join(txt).rstrip())
            elif kind == "error":
                # Never drop these silently: a truncated transcript that looks
                # complete is worse than no transcript, because the workbook
                # tells students to read it when the API is down.
                errors += 1
                tb = "\n".join(o.get("traceback", []))
                lines += ["", f"!! CELL RAISED {o.get('ename', '?')}: "
                              f"{o.get('evalue', '')}", tb, ""]
    if errors:
        lines.insert(4, f"WARNING: {errors} cell(s) raised during capture — "
                        f"this transcript is NOT a clean run.")
    return "\n".join(lines) + "\n"


def main(names):
    OUT.mkdir(parents=True, exist_ok=True)
    written = []
    for name in names:
        nb_path = SOL / f"{name}_solutions.ipynb"
        if not nb_path.is_file():
            print(f"  SKIP {name} (no solutions notebook)")
            continue
        out_path = OUT / f"{name}_expected_output.txt"
        try:
            out_path.write_text(transcript(nb_path))
        except (KeyError, TypeError, ValueError) as e:
            print(f"  SKIP {name} ({type(e).__name__}: {e}) — kept the existing file")
            continue
        written.append(out_path.name)
        print(f"  {out_path.name}")

    # Transcripts nothing can regenerate are how 7.1/7.2/7.3 ended up with
    # hand-maintained files under names no source produces. Report them.
    stale = sorted(p.name for p in OUT.glob("*_expected_output.txt")
                   if p.name not in written)
    if stale:
        print(f"\n  NOTE: {len(stale)} transcript(s) not regenerated by this run:")
        for s in stale:
            print(f"    - {s}")


if __name__ == "__main__":
    main(sys.argv[1:])
