"""
build_notes_ch09.py — rewrite Ch09 speaker notes into delivery structure.

Idempotent: rebuilds decks/1258-Ch09-Summary-Roadmap.pptx from decks/_bak7/
on every run, then applies the 4-element notes (SAY/ASK hook, KEY POINT, TIME,
TRANSITION) and appends preserved markers auto-extracted from the backup.

Run: ../../.venv-courseware/bin/python tools/build_notes_ch09.py
"""
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).parent))
from notes_ch789_common import rebuild, verify, show_samples

DECK = Path(__file__).parent.parent / "decks" / "1258-Ch09-Summary-Roadmap.pptx"

# slide_no -> (device, hook, key_point, time_cue, transition, flex_core)
NOTES = {
1: ("scenario",
    "Three days ago you opened a chat window. Today you leave with a plan your agency can execute.",
    "Closing unit: course synthesis, the verified 2026 trends, the P0-to-P10 re-score, and your 90-day roadmap. If time runs short, the valve: the six flex trend slides and DO NOW 9.D can be skipped without breaking the arc.",
    "(~2 min)",
    "Four objectives to close the course.",
    None),
2: ("ask",
    "What will you be able to do on day 90 that you could not do on Monday?",
    "Synthesize the three days from AI user to AI builder; read the 2026 trends honestly; build a 30/60/90 roadmap; measure your own before-and-after by unsealing P0 and rewriting at P10.",
    "(~2 min)",
    "The shape of the final chapter.",
    None),
3: ("fact",
    "The shortest chapter of the course — and the one your manager will ask about.",
    "Synthesis, honest trends, the capstone debrief, then the roadmap, role-based next steps, and resources — closing with Lab 9.1, your one-page plan.",
    "(~1 min)",
    "The activity list, with the deliverable flagged.",
    None),
4: ("scenario",
    "This chapter's deliverable fits on one page — and you will draft it yourself in Lab 9.1.",
    "70 minutes of activities (63 core): the instructor demo, four Do Nows building toward the roadmap, and the 30-minute Lab 9.1. Full instructions are in your Lab Manual.",
    "(~1 min)",
    "Read the course objectives back — as claims about you.",
    None),
5: ("ask",
    "Hearing these five objectives on Day 1 — which one felt furthest away?",
    "Each objective maps to chapters and labs from the week: foundations (Ch01-02), risk (Ch05), operations (Ch08), data and reporting (Ch06, Ch08), hands-on labs throughout. Read them as claims of competence.",
    "(~2 min)",
    "The three days as a single arc.",
    None),
6: ("fact",
    "AI user on Monday, AI builder on Wednesday — same chair, different professional.",
    "Day 1: foundations, government applications, desktop assistants. Day 2: prompting technique, security and risk, data for AI. Day 3: APIs, RAG, agents, operations — and this roadmap.",
    "(~2 min)",
    "The concept inventory, one slide.",
    None),
7: ("ask",
    "Of everything on this slide — which skill gets used first in your job?",
    "Core concepts (ML, generative AI, operationalization, governance), key skills (visualization, summarization, risk mitigation), and lab highlights (JupyterLab notebooks, desktop assistants, the OpenAI API).",
    "(~2 min)",
    "Now day by day: what you can actually do.",
    None),
8: ("hands",
    "Show of hands — who used an approved assistant for real work before this course? Who feels safer doing it now?",
    "Day 1 deliverables: use desktop AI assistants under your agency's acceptable-use policy, apply the data rule, spot where AI fits government work, and find and assess public datasets such as data.gov.",
    "(~2 min)",
    "Day 2: prompt, judge, secure.",
    None),
9: ("fact",
    "The ladder and the rubric come back this afternoon — your P10 score depends on them.",
    "Day 2 deliverables: climb the prompt ladder from zero-shot to few-shot to role plus format contract; score any output against the rubric; recognize prompt injection, data leakage, and shadow AI; minimize and mask PII.",
    "(~2 min)",
    "Day 3: build and govern.",
    None),
10: ("scenario",
    "This morning you built the thing the trend reports describe — an agent, with guardrails.",
    "Day 3 deliverables: call an LLM API and control cost and behavior, ground answers in your own documents with RAG, keep a human in the agent loop, and monitor, visualize, and explain models in operations. The capstone is the proof point.",
    "(~2 min)",
    "Where agencies are applying all of this.",
    None),
11: ("ask",
    "Which of these use cases maps to something sitting on your desk right now?",
    "Public-health dashboards, generative policy briefs, disaster analytics, finance dashboards — the through-line is faster decision-making and more transparent, engaging government.",
    "(~2 min)",
    "Now with receipts: four verified federal wins.",
    None),
12: ("fact",
    "Years to weeks. 8,000 grant awards in 4 hours. 7,000 labor-days a year.",
    "All four cases come from DOI's public AI strategy (September 2025) — and the pattern is frontline staff with approved tools, not moonshots. That is exactly what your 90-day roadmap replicates.",
    "(~2 min)",
    "The honest half: challenges, risks, and best practices.",
    None),
13: ("scenario",
    "Legacy systems, uneven data, skeptical colleagues — the trio every roadmap has to answer.",
    "Challenges (infrastructure, data quality, resistance), risks (bias, misinformation, security), and best practices (scalable transparent systems, regular audits, cross-agency collaboration) — with the NIST AI RMF, its GenAI Profile, and OMB M-25-21 as the instruments.",
    "(~2 min)",
    "One principle deserves its own slide: explainability.",
    None),
14: ("ask",
    "Could you explain your model's decision to the person it affects?",
    "Explainable AI builds public trust and reduces bias; the ethical frame is fairness, accountability, and transparency — applied wherever benefits allocation or enforcement decisions are automated.",
    "(~2 min)",
    "'Human-in-the-loop' just became policy language.",
    None),
15: ("scenario",
    "When the agent proposes and a person approves, that is not caution — that is compliance.",
    "OMB M-25-21 requires human oversight for high-impact AI, with the ability to intervene and discontinue underperforming systems; commercial agent designs echo it — 'AI enhances, not replaces' is a compliance position, not a slogan.",
    "(~2 min)",
    "The 2026 landscape, honestly.",
    None),
16: ("fact",
    "Three dated trends, no hype: agents that act, models that reason, and weights you can own.",
    "Agentic AI, reasoning plus native multimodality, and open-weight/on-prem viability — the verified mid-2026 picture; the six flex slides that follow give each trend its full treatment with dated numbers.",
    "(~2 min)",
    "First: what 'agentic' actually means.",
    None),
17: ("ask",
    "Workflow or agent — who decided the steps?",
    "Workflows run models along predefined code paths; agents dynamically direct their own process and tool use. Start with the simplest pattern that works — often one good prompt plus retrieval; full agents pay off only when flexibility is needed at scale.",
    "(~2 min if taught)",
    "Second trend: models that think before answering.",
    "workflows are predefined paths and agents direct themselves — start with the simplest pattern that works"),
18: ("fact",
    "These models think longer before answering — and you pay for the thinking.",
    "Test-time compute scales quality on hard problems; reasoning models use tools agentically and can think with images; OpenAI reported o3 made 20% fewer major errors than o1 on hard real-world tasks per external experts; budget the reasoning-effort dial.",
    "(~2 min if taught)",
    "Third trend: one model for every modality.",
    "reasoning models spend compute at answer time for better answers — and the effort dial trades cost against quality"),
19: ("ask",
    "Digitized forms, geospatial maps, Section 508 accessibility — what do they have in common?",
    "All are multimodal problems. Natively multimodal input and output are now standard at the frontier (Gemini 2.0: text, image, video, audio in; image and speech out), and a browser agent prototype scored 83.5% on WebVoyager.",
    "(~2 min if taught)",
    "Fourth trend: serious models you can run yourself.",
    "one model now handles text, image, audio, and video — and frontier agent prototypes act in the world"),
20: ("fact",
    "An 80 GB GPU and an Apache 2.0 license — that is now a serious model inside your boundary.",
    "gpt-oss-120b delivers near-parity reasoning on a single 80 GB GPU; gpt-oss-20b runs on edge devices with 16 GB; full chain-of-thought access and adjustable effort. Federal exemplar: DOI pairs FedRAMP cloud with on-prem HPC for sensitive work.",
    "(~2 min if taught)",
    "The year in four numbers.",
    "capable open-weight models make on-prem deployment realistic for sensitive government data"),
21: ("ask",
    "Which number on this slide will leadership quote back at you?",
    "AI Index (April 2026): 88% of organizations use AI, SWE-bench Verified scores rose from 60% to near 100% in a year, the US-China top-model gap is down to 2.7%, and AI data-center power capacity hit 29.6 GW — capability compounding, resource bills arriving.",
    "(~2 min if taught)",
    "What Gartner is telling your CIO.",
    "capability is still compounding AND the energy and governance bill is arriving — a balanced answer to 'are we behind?'"),
22: ("fact",
    "This is the vocabulary your CIO will bring back from the next conference.",
    "Gartner's 2026 strategic trends (October 2025) in government terms: multiagent systems, domain-specific language models, AI security platforms against prompt injection and data leakage, and digital provenance — each maps to a course chapter.",
    "(~2 min if taught)",
    "Open floor — your questions before the capstone debrief.",
    "the CIO vocabulary for 2026 — multiagent, domain-specific models, AI security platforms, provenance — mapped to course chapters"),
23: ("do",
    "Floor is open — what is still fuzzy: ethics, scalability, your specific use case?",
    "Take questions and feedback; capture recurring themes on the whiteboard and park roadmap-shaped ones for Lab 9.1. Instructor: listen more than you answer; connect each question back to a course chapter.",
    "(~10 min open floor — instructor facilitates, whiteboard captures themes)",
    "Now the ritual you have been waiting three days for.",
    None),
24: ("scenario",
    "Day 1, you sealed a prompt in an envelope. Nobody has peeked — right?",
    "The prompting spine: P0 was your Day-1 baseline, sealed; since then you gained the ladder, the rubric, RAG, and agents; P10 is the same task rewritten with all of it. Then Demo 9.1 — a prompt, three days apart: run the Day-1 prompt live and narrate what changed.",
    "(~2 min setup + Demo 9.1: 8 min — instructor runs the Day-1 prompt live)",
    "Unseal the envelope.",
    None),
25: ("do",
    "Open the envelope. Re-read your Day-1 self. Run it exactly as written — then score it in ink.",
    "Five quiet minutes: re-run the original prompt unchanged in your approved assistant, score the output against the rubric, and write the baseline on the card. Instructor: enforce no-editing, and public or synthetic inputs only.",
    "(5 min quiet re-run + scoring — instructor holds the silence, then polls a few baselines)",
    "Now rewrite it with everything you know.",
    None),
26: ("ask",
    "Which rung of the ladder moves your task the most?",
    "Restate the task zero-shot with audience and constraints; add two few-shot examples; apply the role + format contract; compare a reasoning model on the hard subtask. Score P0 and P10 against the same rubric and debrief the delta — this is DO NOW 9.A.",
    "(~10 min rewrite + debrief — instructor circulates and coaches; the role + format rung usually moves government writing most)",
    "From your prompts to your policy landscape.",
    None),
27: ("fact",
    "One memo shapes your AI working life: a Chief AI Officer, a governance board, an annual inventory, an acceptable-use policy.",
    "OMB M-25-21 (April 2025, replacing M-24-10): high-impact AI carries mandatory minimum practices, agencies publish a public use-case inventory every year, a generative-AI acceptable-use policy is required, and compliance plans refresh every two years through 2036.",
    "(~2 min)",
    "Meet the cast that runs it.",
    None),
28: ("ask",
    "Who is your agency's Chief AI Officer? If you do not know — that is roadmap step one.",
    "The CAIO is accountable for the agency's AI program; the AI Governance Board approves and oversees; the Chief Data Officer owns data quality and access; you are the informed user who spots use cases and flags risks.",
    "(~2 min)",
    "One agency already wrote the playbook — steal it.",
    None),
29: ("fact",
    "GSA already wrote the playbook: a chatbot for everyone, copilots in workflows, high-impact uses under oversight.",
    "Tier 1 enterprise chatbot for all staff, Tier 2 API and agentic integrations, Tier 3 embedded high-impact uses with heightened oversight — on the shared USAi platform with fast '20x' FedRAMP authorization. Copy the tier skeleton directly into your 90-day plan.",
    "(~2 min)",
    "The evaluation instrument for weeks 9-12.",
    None),
30: ("scenario",
    "When leadership asks 'is it safe?', this is the vocabulary they expect in the answer.",
    "The NIST AI RMF is the federal reference for trustworthy AI — Govern, Map, Measure, Manage — with the GenAI Profile enumerating generative risks and free companions (Playbook, Crosswalk, Resource Center); it is under revision as of August 2026.",
    "(~2 min)",
    "The 90-day template itself.",
    None),
31: ("do",
    "Photograph this slide — it is the skeleton of your Lab 9.1 deliverable.",
    "Days 1-30: pick one low-risk use case and confirm data, rules, and sponsor. Days 31-60: prototype with prompting or RAG, human in the loop throughout. Days 61-90: evaluate, document risks and guardrails, brief leadership. Anchors: GSA's tiers, your AUP, the use-case inventory, M-25-21.",
    "(~2 min)",
    "Each block, starting with days 1-30.",
    None),
32: ("ask",
    "What is your most boring recurring task? That is probably your pilot.",
    "High value, low risk — internal productivity before public-facing decisions; confirm the data exists, is usable, and is approved; read your AUP before touching a tool; line up a sponsor and one measurable success; check the use-case inventory for duplicates.",
    "(~2 min)",
    "Days 31-60: prototype, carefully.",
    None),
33: ("scenario",
    "Prompt first; add RAG when answers need your documents; a human reviews every output that leaves your desk.",
    "Prototype with the simplest pattern, log prompts, models, and failure modes, and watch the high-impact trigger — legal or material effects on the public mean you pause and engage your CAIO and governance board.",
    "(~2 min)",
    "Days 61-90: prove it, write it down, brief it.",
    None),
34: ("fact",
    "Success at day 90 is a trusted, documented pilot — not a production launch.",
    "Evaluate outputs against your rubric; document risks and guardrails using the NIST AI RMF as your checklist; write the one-page brief — value, cost, risks, and the next decision — and deliver it to your manager.",
    "(~2 min)",
    "What that looks like by role.",
    None),
35: ("ask",
    "Manager, analyst, IT operations — which row of this slide is yours?",
    "Managers: read the strategy and AUP, approve one Tier 1-style pilot, ask the three questions, protect training time. Analysts: ground one recurring report and verify every figure. IT operations: inventory shadow AI, then offer an approved path.",
    "(~1 min)",
    "The manager's row, up close.",
    None),
36: ("scenario",
    "Three questions kill a bad AI proposal politely: What data? What oversight? What measure of success?",
    "This month: read your agency's AI strategy and acceptable-use policy, approve one Tier 1-style pilot from the 30/60/90 template, and protect training time — the AI Training Act makes that a workforce investment, not a perk.",
    "(~2 min)",
    "The analyst's row.",
    None),
37: ("fact",
    "Repeat P0 to P10 on one real task within 30 days — that is this entire course in miniature.",
    "Analysts convert the course into habit: a personal prompt library with rubric scores attached, every ask grounded RAG-style in source documents, and your best before/after volunteered as a team demo — GSA's Friday Demo Days pattern.",
    "(~2 min)",
    "The IT operations row.",
    None),
38: ("scenario",
    "Find the shadow AI before it finds you — then offer a better, approved path.",
    "IT operations owns the supply side: inventory unapproved tools and offer approved alternatives, know your boundary options (FedRAMP-authorized cloud vs open-weight on-prem), plan for prompt injection, leakage, and provenance checks, and watch capacity and cost as agentic workloads grow.",
    "(~2 min)",
    "The final recap.",
    None),
39: ("ask",
    "Small, ethical, transparent — which of the three is hardest inside your agency?",
    "AI enhances rather than replaces human decision-making — and per M-25-21 that is policy, not preference; pilot AI projects in manageable areas and use clear communication about AI's role in governance.",
    "(~2 min)",
    "Where to keep learning after today.",
    None),
40: ("fact",
    "One classic, one economics lens, and three federal communities that actually exist.",
    "Negnevitsky for classical AI foundations (2011 — predates deep learning), Prediction Machines for the economics; then GSA's AI Community of Practice and AI Training Series, NIST's AI Resource Center, and GSA's AI Guide for Government.",
    "(~2 min)",
    "The training ecosystem, made concrete.",
    None),
41: ("scenario",
    "Friday Demo Days costs nothing to copy — and it is how GSA normalized AI use.",
    "GSA's government-wide AI Training Series — technical, acquisition, and leadership tracks — was established under the AI Training Act; the Community of Practice offers peer support across agencies; start locally.",
    "(~2 min)",
    "Four bookmarks to take home.",
    None),
42: ("do",
    "Four bookmarks — and the last one is the most useful and the least read.",
    "OMB M-25-21, the NIST AI RMF and GenAI Profile, GSA's AI Guide for Government, and your own agency's AI strategy and use-case inventory — every one public.",
    "(~2 min)",
    "The glossary follows — reference, not presentation.",
    None),
43: ("ask",
    "Quick check — who can define 'agent' versus 'agentic workflow' without looking?",
    "Reference slide (A): acceptable-use policy, agent, agentic workflow, AI use-case inventory. For look-up after class, not presented linearly.",
    "(0 min — reference slide; leave up during breaks)",
    "C through F next.",
    None),
44: ("fact",
    "Four terms here did the heavy lifting all week: chain-of-thought, CAIO, embeddings, FedRAMP.",
    "Reference slide (C-F). For look-up after class, not presented linearly.",
    "(0 min — reference slide)",
    "F through H.",
    None),
45: ("ask",
    "Few-shot versus zero-shot — which rung of the ladder is which?",
    "Reference slide (F-H): few-shot prompting, fine-tuning, generative AI, hallucination. For look-up after class, not presented linearly.",
    "(0 min — reference slide)",
    "H through M.",
    None),
46: ("fact",
    "'High-impact' is the term that decides your paperwork — it earns its place here.",
    "Reference slide (H-M): high-impact AI, human-in-the-loop, large language model, multimodal model. For look-up after class, not presented linearly.",
    "(0 min — reference slide)",
    "M through P.",
    None),
47: ("ask",
    "Prompt injection — attack, or just data the model trusted?",
    "Reference slide (M-P): OMB M-25-21, open-weight model, prompt, prompt injection. For look-up after class, not presented linearly.",
    "(0 min — reference slide)",
    "R through S.",
    None),
48: ("fact",
    "RAG, reasoning, rubric, shadow AI — the four R-to-S words of the week.",
    "Reference slide (R-S). For look-up after class, not presented linearly.",
    "(0 min — reference slide)",
    "T through Z.",
    None),
49: ("ask",
    "Temperature up or down for a compliance extraction?",
    "Reference slide (T-Z): temperature, token, workflow vs agent, zero-shot prompting. For look-up after class, not presented linearly.",
    "(0 min — reference slide)",
    "The frameworks row.",
    None),
50: ("fact",
    "This row is the glossary's policy page: AI RMF, explainability, data minimization, provenance.",
    "Reference slide (Frameworks). For look-up after class, not presented linearly.",
    "(0 min — reference slide)",
    "Last lab of the course — your roadmap.",
    None),
51: ("scenario",
    "One page your manager can read in two minutes and act on — that is the assignment.",
    "30 minutes: start from the use case you circled in DO NOW 9.B, find one precedent in federal_ai_use_cases.csv, and draft the days 1-30 block — problem, data, owner. Instructor: circulate and push for a named owner and a real data source; collect two or three to share.",
    "30 min lab — 2 min launch, circulate, 5 min share-out of strong one-pagers.",
    "Close the course.",
    None),
52: ("ask",
    "What is the first thing you will do on Monday morning?",
    "Complete the course evaluation today — it shapes the next revision. Take your P10, the 30/60/90 template, and the bookmark list; stay connected through your agency's AI community and the federal training series.",
    "(~2 min — instructor points to the evaluation form before anyone packs up, and says how the whiteboard export will be shared)",
    "End of course — go build something boring and useful.",
    None),
}


def main():
    rebuild(DECK, NOTES)
    stats = verify(DECK, NOTES, "ch09")
    show_samples(DECK, [17, 24], "ch09")
    return stats


if __name__ == "__main__":
    main()
