"""
build_notes_ch08.py — rewrite Ch08 speaker notes into delivery structure.

Idempotent: rebuilds decks/1258-Ch08-Operations-Reporting.pptx from decks/_bak7/
on every run, then applies the 4-element notes (SAY/ASK hook, KEY POINT, TIME,
TRANSITION) and appends preserved markers auto-extracted from the backup.

Run: ../../.venv-courseware/bin/python tools/build_notes_ch08.py
"""
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).parent))
from notes_ch789_common import rebuild, verify, show_samples

DECK = Path(__file__).parent.parent / "decks" / "1258-Ch08-Operations-Reporting.pptx"

# slide_no -> (device, hook, key_point, time_cue, transition, flex_core)
NOTES = {
1: ("scenario",
    "This morning you built AI. This afternoon: who keeps it alive after the demo ends?",
    "Chapter 8 is operations plus reporting — pipelines, monitoring, oversight, and honest dashboards, Day 3 PM. If we run long, the flex items are the valve: DO NOW 8.B and 8.D, the two drift depth slides, and Lab 8.2 can be trimmed or skipped.",
    "(~2 min)",
    "Four objectives for the afternoon.",
    None),
2: ("ask",
    "What happens to a pilot the day after the pilot team leaves?",
    "Move AI projects from pilots to production; maintain them with monitoring and retraining; govern them with frameworks for transparency and accountability; sustain them with best practices.",
    "(~2 min)",
    "The afternoon's route.",
    None),
3: ("fact",
    "Four stops this afternoon: cloud, MLOps, federal oversight, and reporting that tells the truth.",
    "Cloud foundations, then pipelines and drift, then GAO and OMB oversight, then visualization and GenAI-assisted reporting — with a drift demo, four Do Nows, and two labs.",
    "(~1 min)",
    "The activity budget, up front.",
    None),
4: ("scenario",
    "Two labs this afternoon — and both end with something you could hand a manager.",
    "102 minutes of activities (54 core): a drift demo, four Do Nows, Lab 8.1 on EPA visualization, Lab 8.2 on GenAI-assisted briefing. Full instructions are in your Lab Manual.",
    "(~1 min)",
    "Start underneath everything: the cloud layer.",
    None),
5: ("ask",
    "Why did AI in government take off at exactly the moment cloud did?",
    "AI combined with cloud delivers scalable, on-demand intelligence: global accessibility, high-performance computing, and pay-as-you-go cost — the platform under everything else in this chapter.",
    "(~2 min)",
    "Before the platform, though: the data itself.",
    None),
6: ("fact",
    "Most of an AI project's hours go here — finding what the data says, then making it usable.",
    "Exploratory data analysis surfaces outliers, trends, and predictive features; preparation transforms, cleanses, and encodes. Consistent, accurate data is the entry fee for everything downstream.",
    "(~2 min)",
    "Zoom out: the phases of a machine-learning delivery.",
    None),
7: ("do",
    "Trace the diagram left to right — and mark where your current project actually sits.",
    "The phases map keeps the next slides oriented: every step we discuss plugs into one of these boxes.",
    "(~1 min)",
    "The delivery process as a pipeline.",
    None),
8: ("scenario",
    "No use case, no pipeline — success criteria come before any tooling.",
    "Define the business use case and success criteria first; the delivery steps can run manually or be automated as a pipeline; our focus is the first three: extraction, analysis, preparation.",
    "(~2 min)",
    "Step one: getting the data out.",
    None),
9: ("ask",
    "Streaming sensors or monthly CSVs — which does your mission actually produce?",
    "Extraction spans real-time or batch, structured or unstructured — CRM systems, vehicle sensors, documents, audio, video. Managing these diverse formats is what makes later analysis possible.",
    "(~2 min)",
    "A law that limits how fast all of this can go.",
    None),
10: ("fact",
    "Double the machines, and the sequential part of your job decides how much you gain.",
    "Amdahl's Law: parallel speedup is capped by the sequential portion — in training large models, non-parallelizable work like data preprocessing and model synchronization sets the ceiling.",
    "(~2 min)",
    "The hardware built to push that ceiling: GPUs.",
    None),
11: ("ask",
    "Why does a graphics card run AI better than a server CPU?",
    "GPUs handle the parallel computations deep learning needs (CUDA cores, TensorFlow and PyTorch support) — at real cost and energy draw; cloud accelerated-computing families are the alternative to on-premises hardware.",
    "(~2 min)",
    "Matching capacity to demand: elastic infrastructure.",
    None),
12: ("scenario",
    "Peak season hits and traffic triples — does your infrastructure notice by itself?",
    "Training frontier-class models takes enormous compute; elastic infrastructure scales up during peak demand and down during idle, optimizing cost and handling spikes and long-running jobs (AWS Batch, Vertex AI Workbench).",
    "(~2 min)",
    "Who in government is actually doing this?",
    None),
13: ("fact",
    "CDC reads pathology reports with NLP; DHS publishes every AI use case in a public inventory.",
    "Applied AI is operational today: CDC's eMaRC Plus identifies reportable cancer cases from pathology reports; DHS's use-case inventory is framed by OMB M-25-21's high-impact rules; agencies pair FedRAMP-authorized cloud with on-prem/HPC for sensitive workloads.",
    "(~2 min)",
    "Running models like this takes a discipline — MLOps.",
    None),
14: ("ask",
    "Who owns a model after the data scientist demos it?",
    "MLOps unites data science, IT operations, and business stakeholders to deploy, monitor, and govern AI — robust, reliable, compliant systems that improve decision-making and citizen services.",
    "(~2 min)",
    "What MLOps actually buys you.",
    None),
15: ("fact",
    "CI/CD is not just for software anymore — models get versions, tests, and rollback too.",
    "Automation of training, testing, and deployment; CI/CD for rapid iteration; continuous monitoring for drift and bias; scalability across agencies; version control for models and data.",
    "(~2 min)",
    "The pipeline, properly introduced.",
    None),
16: ("scenario",
    "A pipeline is the difference between 'it worked on my laptop' and 'it works every night.'",
    "An ML pipeline is a structured workflow for designing, training, evaluating, and deploying models — delivering automation, reproducibility, scalability, and efficiency.",
    "(~2 min)",
    "The seven steps inside it.",
    None),
17: ("do",
    "Read the seven steps as a checklist — which one does your shop skip today?",
    "Collect, preprocess, engineer features, train, evaluate, deploy, monitor — each step is automatable, and monitoring closes the loop back to the start.",
    "(~2 min)",
    "The tools that implement each step.",
    None),
18: ("ask",
    "If your agency standardized on one pipeline ecosystem tomorrow, which would it be?",
    "Python libraries (scikit-learn, TensorFlow, PyTorch, Pandas); frameworks (Airflow, Kubeflow, MLflow, TFX); cloud services (SageMaker, Google Cloud AI, Azure ML) — same pipeline, many stacks.",
    "(~2 min)",
    "Pipelines that retrain themselves: CI/CD plus continuous training.",
    None),
19: ("fact",
    "The best pipelines retrain themselves — on new data, automatically, with gates that catch bad models.",
    "CI/CD for ML automates testing and deployment of data, code, and models; continuous training re-runs on new data; version all three together for audit; automated gates keep weak models out of production.",
    "(~2 min)",
    "Which brings us to the real goal: operationalizing AI.",
    None),
20: ("ask",
    "What is the graveyard of government AI? Pilots that never shipped.",
    "Operationalization moves AI from experimental pilots to production — scalability, reliability, and real-world impact in disaster response, citizen services, and infrastructure, maximizing ROI on AI investments.",
    "(~2 min)",
    "A concrete use case: smarter public-service announcements.",
    None),
21: ("scenario",
    "A health campaign has five messages and one homepage slot — which message for which visitor?",
    "Contextual bandits: read the user's context, choose an action (which PSA to show), measure reward (engagement) — the algorithm adapts delivery so critical messages reach the right audience at the right time.",
    "(~2 min)",
    "Why most pilots stall on the way to production.",
    None),
22: ("ask",
    "Which kills more projects — the technology, or the organization?",
    "Technical barriers (compute, legacy integration), organizational challenges (skills gap, resistance), and performance issues (drift, limited real-world testing) — plan for all three.",
    "(~2 min)",
    "The flip side: what makes deployments succeed.",
    None),
23: ("fact",
    "Production-grade means three words: scales, survives, integrates.",
    "Scalability via cloud infrastructure and modular design; resilience via redundancy and stress tests; integration via middleware and personnel trained to act on AI outputs.",
    "(~2 min)",
    "Even a successful model decays — drift.",
    None),
24: ("scenario",
    "Fraud patterns evolve and demographics shift — your model still thinks it is training day.",
    "Concept drift changes the relationship between inputs and outputs; data drift changes the input distribution itself. Automate detection (tools like Alibi Detect) and schedule periodic retraining with updated data.",
    "(~2 min)",
    "The full lifecycle — including the end of it.",
    None),
25: ("ask",
    "Does your agency have a plan to retire a model — or only to launch one?",
    "Manage deployment, monitoring, updates, and decommissioning deliberately: rigorous testing before production, real-time metrics, retraining cycles, and clear retirement criteria with seamless transitions.",
    "(~2 min)",
    "What to track while it runs.",
    None),
26: ("fact",
    "GAO names monitoring one of four federal AI accountability principles — this slide is that principle in practice.",
    "Track accuracy and precision, latency, and reliability; use dashboards, automated alerts for drops and anomalies, and platforms like Prometheus and Grafana.",
    "(~2 min)",
    "The production monitoring checklist.",
    None),
27: ("scenario",
    "Define the retirement condition before deployment — not after the bad headline.",
    "Monitor model performance against a known baseline, input data health, pipeline health, and mission outcomes; set drift detection and retraining triggers before deployment, per GAO's accountability framework.",
    "(~2 min)",
    "A deeper cut on drift and hidden debt.",
    None),
28: ("fact",
    "Your model's own outputs can become its future training data — a feedback loop nobody declared.",
    "Detectors exist — statistical tests like KS, MMD, and chi-squared (Alibi Detect); the deeper lesson is hidden technical debt: feedback loops and undeclared consumers quietly depending on your model.",
    "(~2 min if taught)",
    "Then: when to retrain, and when to retire.",
    "drift has statistical detectors, and ML systems accrue hidden technical debt you must hunt"),
29: ("ask",
    "Retrain every quarter on the calendar — or only when the metrics say so?",
    "Scheduled retraining is predictable but may fire needlessly; triggered retraining responds to real drift but needs reliable monitoring; validate the retrained model before it replaces production, and retire models whose mission has ended — NIST AI RMF's Manage function.",
    "(~2 min if taught)",
    "From maintaining models to overseeing the whole program.",
    "retrain on a schedule or on triggers, validate before replacing, and retire models whose mission or data has ended"),
30: ("fact",
    "Three names cover most of federal AI oversight: GAO's framework, NIST's AI RMF, and OMB M-25-21.",
    "Oversight rests on regular risk audits guided by GAO's accountability framework, the NIST AI RMF, and M-25-21's rules for high-impact AI — delivering transparency, fairness, and accountability.",
    "(~2 min)",
    "The audit-ready checklist, principle by principle.",
    None),
31: ("ask",
    "Is your AI 'high-impact'? The answer decides your paperwork.",
    "GAO-21-519SP's four principles — governance, data, performance, monitoring — carry key practices and audit questions; M-25-21 defines high-impact AI (output driving decisions affecting rights or safety) and requires minimum risk-management practices; the NIST AI RMF sits underneath both.",
    "(~2 min)",
    "Mid-chapter reset: the same objectives, now for reporting.",
    None),
32: ("scenario",
    "Halfway mark: operations covered — now the same discipline applied to reporting.",
    "The second half applies the operational mindset to reporting: from pilot-quality charts to production-quality communication, under the same oversight frame.",
    "(~1 min)",
    "First, reporting itself needs a promotion.",
    None),
33: ("ask",
    "Is your quarterly report steering anything — or just documenting?",
    "Treat reporting as strategy, not compliance: actionable insights aligned with organizational goals, decision support at all levels, unified metrics, and groundwork for predictive and prescriptive analytics.",
    "(~2 min)",
    "Every honest report starts with honest data.",
    None),
34: ("fact",
    "Every trustworthy dashboard is boring underneath: accurate, consistent, complete.",
    "Data integrity means accuracy, consistency, and completeness — achieved with AI-driven correction tools, real-time schema validation, and collaborative governance with domain experts.",
    "(~2 min)",
    "The price of getting that wrong.",
    None),
35: ("scenario",
    "A bad number in a report does not stay in the report — it becomes a decision, then a finding.",
    "Poor data drives ineffective decisions, downstream rework costs, and regulatory penalties; quality data reduces risk, supports advanced analytics, and builds trust across teams and stakeholders.",
    "(~2 min)",
    "Now make the good data legible: visualization.",
    None),
36: ("ask",
    "Florence Nightingale argued with a diagram instead of a memo — which would move your leadership?",
    "Visualization converts metrics into actionable insights for diverse stakeholders and reveals trends and outliers fast; keep it simple, tailor it to the audience, and design with human perception.",
    "(~2 min)",
    "How people actually see: six gestalt principles.",
    None),
37: ("do",
    "Six principles your reader's brain applies before reading a single word.",
    "Proximity, similarity, enclosure, closure, continuity, connection — layout choices trigger grouping automatically, so design with them, not against them.",
    "(~1 min)",
    "From perception to practice: the guidelines.",
    None),
38: ("fact",
    "'Start with grey' — color is a budget; spend it on the one thing that matters.",
    "Show the data, provoke thought, avoid distortion, integrate graphics and text, reduce clutter, skip spaghetti charts, and weave the narrative — the checklist Lab 8.1 applies.",
    "(~2 min)",
    "One more foundation: knowing your data landscape.",
    None),
39: ("scenario",
    "Internal CRM, external APIs, ETL in between — and the Privacy Act over all of it.",
    "Know your internal and external sources, standardize through ETL pipelines, and govern with the Privacy Act, FISMA, and HIPAA where health data is involved — with named data stewards.",
    "(~2 min)",
    "Put it to work on real data — Lab 8.1.",
    None),
40: ("do",
    "Lab Manual, Lab 8.1 — real EPA air-quality data becomes a one-page briefing.",
    "30 minutes: rank counties by unhealthy days, chart the top 15 sorted, labelled, and on an honest scale, then assemble a one-page briefing with a recommendation. Instructor: circulate and enforce the honest-scale guideline; hold 3 minutes to show one strong student briefing.",
    "30 min lab — 2 min launch, circulate, 3 min show-and-tell at the end.",
    "What dashboards do with charts like these.",
    None),
41: ("ask",
    "What did the public dashboards of the pandemic change more — the data, or the trust?",
    "Dashboards drive decision-making (patterns, anomalies, KPIs) and public transparency (real-time data on key initiatives) — building public trust and enabling timely interventions.",
    "(~2 min)",
    "The tools people build them with.",
    None),
42: ("fact",
    "Google renamed its BI tool back to Data Studio in April 2026 — third name, same product.",
    "Tableau for highly interactive custom visuals, Power BI where Microsoft 365 is standard, Data Studio for quick, cost-effective reporting — all three now ship AI capabilities like anomaly detection.",
    "(~2 min)",
    "The AI inside Power BI — with a government caveat.",
    None),
43: ("scenario",
    "Your tenant is Azure Government — read the fine print before promising anyone a Copilot demo.",
    "Copilot in Power BI answers in natural language but requires paid Fabric capacity (F2+) or Premium (P1+) — and, as of mid-2026, is not supported in sovereign clouds; prep semantic models for AI and verify answers before relying on them.",
    "(~2 min)",
    "Under any tool: the components of an effective dashboard.",
    None),
44: ("ask",
    "Who is your dashboard's end user — and what must they grasp in the first five seconds?",
    "Data accurate, timely, and relevant; layout with critical information on top and clean, consistent design; interactivity through filters and drilldowns from summary to detail.",
    "(~2 min)",
    "Best practice, distilled to one slide.",
    None),
45: ("fact",
    "Start with the decision, not the data — a beautiful dashboard over inconsistent definitions erodes trust fastest.",
    "One message per view with the headline metric first; consistent definitions and time grains across reports; anomalies and known gaps annotated directly; test every dashboard with real users before rollout.",
    "(~2 min)",
    "Where AI takes reporting next: real time.",
    None),
46: ("scenario",
    "Emergency response times creep upward for a week — does anyone's dashboard notice before the briefing?",
    "AI automates update pipelines and runs real-time anomaly detection and trend identification — already applied to emergency response times and public-health monitoring.",
    "(~2 min)",
    "A scenario that pulls it together.",
    None),
47: ("ask",
    "Fragmented feeds in a disaster — what would one live dashboard change for your region?",
    "Walk the illustrative scenario: AI-driven dashboards integrating live weather and field reports give unified situational awareness and automated prioritization — faster response through integration, no invented numbers.",
    "(~2 min)",
    "Now generative AI enters the reporting workflow.",
    None),
48: ("fact",
    "Upload the CSV, ask for the profile, the trend, and the chart — then verify every figure.",
    "Modern BI tools embed AI (Copilot, natural-language queries); assistants profile and chart your data in plain language — the modern complement to this chapter's Python skills, with verification still on you.",
    "(~2 min)",
    "The verification habit, made concrete.",
    None),
49: ("do",
    "Always ask the tool to show the query or code it actually ran.",
    "Schema-correct output is not necessarily semantically correct: spot-check against a known subset of your data, treat AI-generated insight as a draft until a human validates it, and use public or approved data only.",
    "(~2 min)",
    "Practice the habit — Lab 8.2.",
    None),
50: ("scenario",
    "Same EPA data, same briefing — but now an assistant drafts, and you do the verifying.",
    "30 minutes: send a profile of the EPA data, get five candidate findings, pick the three most decision-relevant. Instructor: have students compare against their Lab 8.1 manual results — the debrief is what the assistant got wrong and how they caught it.",
    "30 min lab — 2 min launch, circulate, debrief on verification catches.",
    "The chapter in one slide.",
    None),
51: ("ask",
    "What is the first reporting workflow you would optimize back home?",
    "Quality data, intuitive and interactive dashboards, AI for real-time updates and anomaly detection, user-centric design — dashboards as decision systems, not decoration.",
    "(~2 min)",
    "Final chapter: your 90-day roadmap.",
    None),
}


def main():
    rebuild(DECK, NOTES)
    stats = verify(DECK, NOTES, "ch08")
    show_samples(DECK, [28, 40], "ch08")
    return stats


if __name__ == "__main__":
    main()
