"""New Ch03 'Desktop GenAI: Everyday AI for Government Staff' (all new, ~24 slides)
and the Ch00 course-launch additions. Addresses Bill Appelbe's #1 gap: the tools
government staff actually use daily. Content is author input; Pubs styles it."""

CH03_TITLE = "Desktop GenAI: Everyday AI for Government Staff"

CH03_SLIDES = [
 ("Desktop GenAI: Everyday AI for Government Staff",
  ["Chapter objectives:",
   "Recognize the four assistants government staff use daily and their government editions",
   "Apply GenAI to five everyday work patterns",
   "Understand free vs. paid vs. enterprise tiers — and the data rule that governs them",
   "Use AI safely: public data only, human review, awareness of shadow AI"],
  "Chapter opener. This chapter fills the gap instructors flagged: the course taught models and code "
  "but not the desktop assistants staff actually use. Keep it practical and hands-on (Lab 3.1)."),
 ("Why Desktop GenAI Matters for Government",
  ["Most government staff meet AI through a chat assistant, not a Python notebook",
   "They use it daily for research, writing, and summarizing",
   "This is where the productivity and the risk both live",
   "Teaching the tool they actually use is what makes this course stick"],
  "Bill Appelbe: 'that's what gov staff use daily.' Set the frame."),
 ("The Four Assistants",
  ["ChatGPT (OpenAI) — the most widely known general assistant",
   "Microsoft 365 Copilot — embedded in Word, Excel, Outlook, Teams",
   "Google Gemini — in Workspace and the browser",
   "Anthropic Claude — strong writing and analysis",
   "All four are capable; the right one is often the one your agency has licensed"],
  "Answer Greg Adams' question about 'which account to use': it depends on your agency's license. Neutral framing."),
 ("Government and Enterprise Editions",
  ["ChatGPT Gov / Enterprise — admin controls, data not used for training",
   "Microsoft 365 Copilot (GCC / GCC High) — inside the government cloud",
   "Gemini for Google Workspace (Assured/Gov) — enterprise data protections",
   "The edition, not the brand, determines what data you may use"],
  "Emphasize: enterprise/gov editions come with data-protection agreements the free tiers lack."),
 ("FedRAMP and Where Your Data Goes",
  ["FedRAMP authorization tells you a service meets federal security requirements",
   "Public/free assistants are generally NOT authorized for nonpublic data",
   "Enterprise gov editions run inside authorized boundaries (Azure Gov, Google Assured, etc.)",
   "Know your agency's authorized tool list before you paste anything sensitive"],
  "Connect to the Chapter 5 compliance material and the AI acceptable-use policy."),
 ("Everyday Pattern 1: Research and Explanation",
  ["Ask for plain-language explanations of unfamiliar topics, policies, or acronyms",
   "Ask follow-up questions to go deeper",
   "Always verify facts against an authoritative source — the model can be confidently wrong",
   "Great for getting oriented fast; not a citation of record on its own"],
  ""),
 ("Everyday Pattern 2: Summarization",
  ["Summarize long public reports, meeting notes, or email threads",
   "Ask for the summary in a specific form: 5 bullets, an executive paragraph, action items",
   "Public documents only unless you are in an approved enterprise tool",
   "Review the summary — check that nothing important was dropped or distorted"],
  ""),
 ("Everyday Pattern 3: Drafting and Rewriting",
  ["Draft routine correspondence, then edit — the model gives you a first draft, not the final word",
   "Rewrite for tone, reading level, or length ('rewrite for a 6th-grade reading level')",
   "You remain accountable for accuracy and appropriateness",
   "AI-assisted correspondence that documents agency business is a federal record"],
  ""),
 ("Everyday Pattern 4: Diagrams from Text",
  ["Generate process flows and org charts by describing them in words",
   "Ask for Mermaid or a described diagram you can paste into your tools",
   "Fast way to turn a paragraph of process into a picture",
   "Covered hands-on in Lab 3.1"],
  "Ties to the structured-output/Mermaid material in Chapter 4."),
 ("Everyday Pattern 5: Code and Troubleshooting Help",
  ["Explain an error message; suggest a fix; write a small script",
   "Explain what a piece of code or a formula does",
   "Verify and test any code before you run it on real systems",
   "Useful even for non-developers doing light automation (e.g., Excel formulas)"],
  ""),
 ("Free, Paid, and Enterprise Tiers",
  ["Free: fine for learning and public data; consumer terms; no data agreement",
   "Paid individual: higher limits and newer models; still consumer terms",
   "Enterprise/Government: admin control, data protection, FedRAMP posture",
   "The tier controls what data you may enter — not which model is 'smartest'"],
  "This is the 'free vs paid tiers' item Bill asked for, from the staff-tool angle."),
 ("The Data Rule (Non-Negotiable)",
  ["Never paste nonpublic information into a tool not approved for it",
   "No PII, procurement-sensitive, law-enforcement, or classified data in public assistants",
   "Public data (e.g., data.gov, published reports) is fine in any approved tool",
   "Pasting a constituent record into a public chatbot is a reportable data spill"],
  "Andrew Tait's compliance guardrail, stated as course doctrine. Repeat it every time a lab uses an assistant."),
 ("Shadow AI: The Risk of Unofficial Tools",
  ["'Shadow AI' = staff using unapproved AI tools for work, outside IT's visibility",
   "Well-intentioned, but it moves agency data into unmanaged services",
   "The fix is not banning AI — it is providing approved tools and clear rules",
   "Report tools you wish you had; don't route around the policy"],
  "Andrew Tait / Ruchi Gupta both raised shadow-AI concerns. Frame constructively."),
 ("When NOT to Use a Desktop Assistant",
  ["When the data is sensitive and the tool isn't approved for it",
   "When you cannot verify the output and the stakes are high",
   "When a deterministic tool (a form, a calculator, a database query) is the right answer",
   "Good judgment about when to reach for AI is a professional skill"],
  "Bridge to the 'when LLM vs when classic tool' theme that recurs in Ch04/Ch07."),
 ("Lab 3.1: Desktop GenAI Task Relay",
  ["Four timed tasks with a real assistant: summarize, diagram, troubleshoot, draft",
   "Use your agency's approved assistant; public/synthetic inputs only",
   "Score each output against a short quality rubric; compare tools on a shared board",
   "See Workbook Lab 3.1"],
  "Launcher. Debrief: where tools differed; what your AUP allows; free-vs-paid friction observed."),
]

# --- Ch00 additions (appended after the existing 4 intro slides) ---
CH00_ADDITIONS = [
 ("Your Lab Environment: CloudShare",
  ["Your labs run on a CloudShare virtual machine, reached through your browser",
   "You do not install anything — everything is set up for you",
   "Do NOT click the RDP button — use the in-browser Viewer only",
   "The next slides get you in and running before Chapter 1"],
  "DONOW slide 1. The RDP-button warning addresses Greg Adams' note that the button shows but errors. "
  "Instructor: circulate and confirm everyone is in before proceeding."),
 ("Getting In",
  ["1. Sign in to your My Learning Tree account",
   "2. Open the course page and click Launch Lab; wait for the VM to be ready",
   "3. Click the in-browser Viewer to reach your VM desktop",
   "4. Firefox opens automatically to the lab environment"],
  "DONOW slide 2 — Greg Adams' step list, cleaned up. Post-VM-fix, students should not need a terminal."),
 ("Starting the Labs",
  ["Firefox opens to JupyterLab automatically (bookmark: 'Course Labs')",
   "If it doesn't, double-click the 'Start Labs' icon on the desktop",
   "If you are ever asked for a password, it is: pw",
   "You should see a file list of lab notebooks"],
  "DONOW slide 3. The legacy ./run_labs.sh + password lives only here as a fallback; autostart is the front door."),
 ("DO NOW: Run the Healthcheck",
  ["Open lab_0.1_healthcheck.ipynb from the file list",
   "Run menu -> Run All Cells",
   "Confirm the first checks say PASS (green)",
   "Raise your hand if you see any red FAIL — your instructor has a fix"],
  "DONOW slide 4. The healthcheck notebook (Lab 0.1) is the tech check. Do not start Chapter 1 until the room is green."),
 ("AI Accounts and Data Rules This Week",
  ["Use the AI assistant account your instructor designates for class demos",
   "Public or synthetic data only — never paste real agency or personal data",
   "This rule holds for every lab that uses an AI assistant",
   "It mirrors your agency's acceptable-use policy"],
  "Answers Greg Adams' 'which ChatGPT account?' question and states the data rule up front. Andrew Tait's guardrail."),
 ("How We Learn: Bloom's Taxonomy",
  ["This course moves you up Bloom's levels: Remember -> Understand -> Apply -> Analyze -> Evaluate -> Create",
   "Lectures build understanding; labs move you to Apply and Analyze",
   "The capstone agent lab reaches Create",
   "Watch for the level each activity targets"],
  "Formalizes Bloom's, which Greg noted Imran teaches from memory. Now it's in the deck for any instructor."),
 ("Working Together: The Class Whiteboard",
  ["We use a shared whiteboard (Mural) for discussions and lab debriefs",
   "Your instructor will share the board link",
   "Add your ideas on sticky notes; we review as a group",
   "Several labs end with a whiteboard debrief"],
  "Introduces the Mural/whiteboard pattern Bill Appelbe requested for discussions and debriefs."),
 ("Course Roadmap",
  ["Day 1: Foundations, applications, desktop GenAI",
   "Day 2: Prompt engineering, security, and data for AI",
   "Day 3: Building with LLMs — APIs, RAG, and agents — plus operations",
   "Hands-on labs throughout; a capstone agent build on Day 3"],
  "Course map so students see the arc. Reflects the new Ch00-Ch09 structure."),
]
