"""New authored slides for Ch04 'Modern GenAI & Prompt Engineering'.
Each item: (title, [bullets], "speaker notes"). Appended after the kept prompt-
engineering slides harvested from old Ch06. Content is author input; Pubs applies
the course template."""

NEW_SLIDES = [
 # --- 4.2 The 2026 model landscape (replaces old s6 ChatGPT/DALL-E/Bard) ---
 ("The 2026 Model Landscape",
  ["Frontier proprietary models: OpenAI GPT-5 / GPT-4o family, Anthropic Claude, Google Gemini",
   "Open-weight models you can self-host: Meta Llama, Mistral, and others",
   "Multimodal is now standard: text, images, audio, and documents in one model",
   "The field moves fast — this course pins model names in one place so labs stay current"],
  "Replaces the old slide that named only ChatGPT, DALL-E, and 'Bard' (renamed Gemini in Feb 2024). "
  "Emphasize categories over specific versions; the specific names will change."),
 ("Proprietary vs. Open-Weight Models",
  ["Proprietary (API only): best quality, no infrastructure to run, data leaves your boundary unless using a gov/enterprise tier",
   "Open-weight (downloadable): run inside your own boundary, full control, you own the ops and the GPUs",
   "Government pattern: proprietary via FedRAMP'd Azure OpenAI / Bedrock, or open-weight on-prem for sensitive workloads",
   "Decision driver: data sensitivity and control, not just benchmark scores"],
  "Tie to Andrew Tait's guardrail: for sensitive data, where the model runs matters more than which model."),
 ("Free, Paid, and Enterprise Tiers",
  ["Free web tiers: fine for learning and public data; no data-protection agreement",
   "Paid individual: higher limits, still consumer terms",
   "Enterprise / Government (ChatGPT Gov, Copilot GCC, Gemini for Workspace): data-protection agreements, admin controls, FedRAMP status",
   "Rule of thumb: the tier determines what data you may put in — not the model"],
  "This is the 'free vs paid tiers' item Bill Appelbe asked for. Connect to the Chapter 3 data rule."),
 ("Context Windows: How Much the Model Can 'See'",
  ["The context window is how much text the model can consider at once (prompt + conversation + documents)",
   "Modern windows are large (hundreds of thousands of tokens) but not infinite",
   "Big windows enable pasting whole policies — but cost and latency grow with size",
   "When documents exceed the window, you retrieve the relevant parts (RAG, Chapter 7)"],
  "Sets up RAG as the answer to 'my corpus is bigger than the window'."),
 ("Reading a Model Card",
  ["A model card documents intended use, training data at a high level, limitations, and evaluations",
   "Check: supported languages, known failure modes, safety testing, and cutoff date",
   "For government use, also check the provider's data-handling and FedRAMP posture",
   "Model cards are part of responsible procurement, not just engineering"],
  "Frame as due diligence a gov IT professional should do before adopting a model."),

 # --- 4.4 (new part) From CoT to reasoning models ---
 ("From Chain-of-Thought to Reasoning Models",
  ["Chain-of-thought (previous slides) is a manual trick: you ask the model to 'think step by step'",
   "Reasoning models (OpenAI o-series, Claude extended thinking, Gemini thinking) do this internally",
   "You often no longer hand-craft the reasoning — you ask the question and the model reasons",
   "This is one of the biggest shifts since this course was first written"],
  "REFRAME the old CoT slides (kept just before this) as historical technique; reasoning models are the current state."),
 ("What 'Thinking' Models Actually Do",
  ["They spend more computation before answering, exploring and checking their own steps",
   "Strong on multi-step reasoning: policy analysis, math, code, planning",
   "They expose a 'reasoning effort' control — more effort, better answers, higher cost and latency",
   "Not always needed: simple lookups and drafting don't require a reasoning model"],
  "Give a government example: multi-criteria eligibility determination benefits from reasoning; a form-letter draft does not."),
 ("When Manual Step-by-Step Still Helps",
  ["Non-reasoning models still benefit from 'show your work' prompting",
   "Even with reasoning models, asking for structured steps aids transparency and review",
   "For auditable government decisions, seeing the reasoning matters as much as the answer",
   "Match the technique to the model and to the accountability need"],
  "Balance: reasoning models reduce but don't eliminate the value of explicit-reasoning prompts."),
 ("Cost, Latency, and Effort Controls",
  ["Reasoning models cost more and respond slower — budget for it",
   "Use the effort/verbosity controls to dial cost against quality",
   "Reserve high effort for hard, high-stakes tasks; use fast models for routine work",
   "Measure: the token/cost printout in Lab 7.1 shows exactly what you are spending"],
  "Forward-reference Lab 7.1's cost math."),

 # --- 4.6 Role, format, structured-output prompting ---
 ("Role and System Prompting",
  ["The system prompt sets the assistant's role, rules, and boundaries for the whole conversation",
   "'You are a FOIA officer. Cite the exemption for every redaction.' shapes every answer",
   "Roles improve consistency far more than restating instructions in each message",
   "In code (Chapter 7) the system prompt is the first message you send"],
  "This is the 'role prompting' addition. Lab 4.1 exercises it directly."),
 ("Controlling the Output Format",
  ["Ask for exactly the shape you need: a table, a numbered list, a one-paragraph summary, JSON",
   "State length and audience: 'under 150 words, for a non-technical reader'",
   "Give a template and the model fills it in — reduces cleanup",
   "Format control is the difference between a demo and a usable work product"],
  ""),
 ("Structured Outputs: JSON, Tables, and Diagrams",
  ["Ask for JSON when the output feeds another system (Lab 7.1 does this against a memo)",
   "Ask for a Markdown table when a person needs to compare items",
   "Ask for Mermaid syntax to generate process or org diagrams from text",
   "Structured output turns the model from a chat toy into a component in a workflow"],
  "Mermaid diagram generation is one of the 'daily patterns' from Chapter 3 (Desktop GenAI)."),
 ("Grounding: 'Answer Only From This Document'",
  ["Paste a source and instruct: 'Answer only from the text above; if it is not there, say so'",
   "Grounding cuts hallucination and produces citable answers",
   "This is RAG in miniature — Chapter 7 automates it over many documents",
   "For government work, grounded + cited beats fluent + unsourced every time"],
  "On-ramp to the RAG section in Chapter 7. Tie to Andrew Tait: verify, don't trust at face value."),
 ("Putting It Together: A Prompt Contract",
  ["Combine role + task + context + format + constraints into one reusable prompt",
   "Example: role (analyst) + task (summarize) + context (the memo) + format (5 bullets) + constraint (plain language)",
   "A good prompt is a small specification, not a wish",
   "Save your best contracts as templates (next section)"],
  ""),

 # --- 4.8 (new part) Evaluating outputs (s83, s84 kept before this) ---
 ("Evaluating AI Outputs",
  ["Fluent does not mean correct — every output needs review before use",
   "Define what 'good' looks like before you prompt: accuracy, completeness, format, tone",
   "Score outputs against that rubric (Lab 4.1 uses a 1-5 rubric)",
   "Evaluation is how you improve prompts systematically instead of by vibe"],
  "Introduces rubric thinking used in Lab 4.1."),
 ("Rubric-Based Evaluation and LLM-as-Judge",
  ["A rubric turns 'better' into measurable criteria you can score 1-5",
   "You can even ask a second model to score outputs against your rubric (LLM-as-judge)",
   "Useful for comparing prompt versions or models at scale",
   "Always keep a human in the loop for consequential judgments"],
  ""),
 ("Verification Habits for Government Work",
  ["Check facts against authoritative sources — the model can be confidently wrong",
   "Require citations for any factual claim that will be published",
   "Keep a record: AI-assisted work products may be federal records",
   "You, not the tool, are accountable for accuracy"],
  "Reinforces the acceptable-use themes; ties to the AI AUP corpus doc used in labs."),

 # --- 4.9 Lab launcher ---
 ("Lab 4.1: Prompt Engineering Studio",
  ["Improve real outputs through iteration against a scoring rubric",
   "Ladder: zero-shot -> few-shot -> role + format contract -> reasoning-model comparison",
   "Real source documents provided: a dataset description, a policy memo, constituent complaints",
   "Deliverable: before/after prompt pairs with rubric scores. See your Workbook, Lab 4.1"],
  "This replaces the old vague Lab 6.1. Real documents and a rubric address Bill Appelbe's critique. "
  "Debrief: which rung bought the most quality; when to stop iterating and switch approach (bridge to Ch07)."),
]
